import { EnvVarItem } from './env-types'

export function createEnvTemplateSnippet(scope: 'community' | 'commercial' | 'all', attentionVars: EnvVarItem[]): string {
    const lines = [
        '# ─────────────────────────────────────────────────────────────────',
        `# TeamVault ${scope === 'community' ? 'Community' : scope === 'commercial' ? 'Commercial' : 'All'} Missing Environment Variables`,
        '# Generated by Master Admin at ' + new Date().toLocaleString(),
        '# ─────────────────────────────────────────────────────────────────',
        '',
    ]

    attentionVars.forEach(v => {
        lines.push(`# ${v.name} (${v.service}) - ${v.requirement.toUpperCase()}`)
        lines.push(`# ${v.description}`)
        lines.push(`# How to get: ${v.howToGet}`)
        lines.push(`${v.name}=${v.example}`)
        lines.push('')
    })

    return lines.join('\n')
}
