// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseFolder(arg1) {
  return window['go']['main']['App']['ChooseFolder'](arg1);
}

export function ClearSyncLog() {
  return window['go']['main']['App']['ClearSyncLog']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDeviceName() {
  return window['go']['main']['App']['GetDeviceName']();
}

export function GetExcludedFolders(arg1) {
  return window['go']['main']['App']['GetExcludedFolders'](arg1);
}

export function GetFolderTree(arg1) {
  return window['go']['main']['App']['GetFolderTree'](arg1);
}

export function GetSyncLog() {
  return window['go']['main']['App']['GetSyncLog']();
}

export function GetSyncStatus(arg1) {
  return window['go']['main']['App']['GetSyncStatus'](arg1);
}

export function GetTvIgnore(arg1) {
  return window['go']['main']['App']['GetTvIgnore'](arg1);
}

export function GetWorkspaces() {
  return window['go']['main']['App']['GetWorkspaces']();
}

export function IsLoggedIn() {
  return window['go']['main']['App']['IsLoggedIn']();
}

export function IsWatching(arg1) {
  return window['go']['main']['App']['IsWatching'](arg1);
}

export function Login() {
  return window['go']['main']['App']['Login']();
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function SaveSettings(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SaveSettings'](arg1, arg2, arg3, arg4, arg5);
}

export function SaveTvIgnore(arg1, arg2) {
  return window['go']['main']['App']['SaveTvIgnore'](arg1, arg2);
}

export function SetDeviceName(arg1) {
  return window['go']['main']['App']['SetDeviceName'](arg1);
}

export function SetExcludedFolders(arg1, arg2) {
  return window['go']['main']['App']['SetExcludedFolders'](arg1, arg2);
}

export function SetScheduleInterval(arg1, arg2) {
  return window['go']['main']['App']['SetScheduleInterval'](arg1, arg2);
}

export function StartWatcher(arg1) {
  return window['go']['main']['App']['StartWatcher'](arg1);
}

export function StopWatcher(arg1) {
  return window['go']['main']['App']['StopWatcher'](arg1);
}

export function SyncNow(arg1) {
  return window['go']['main']['App']['SyncNow'](arg1);
}
