// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ChooseFolder(arg1:string):Promise<string>;

export function ClearSyncLog():Promise<void>;

export function GetConfig():Promise<Record<string, any>>;

export function GetDeviceName():Promise<string>;

export function GetExcludedFolders(arg1:string):Promise<Array<string>>;

export function GetFolderTree(arg1:string):Promise<Array<main.FolderNode>>;

export function GetSyncLog():Promise<Array<main.LogEntry>>;

export function GetSyncStatus(arg1:string):Promise<main.SyncStatusInfo>;

export function GetTvIgnore(arg1:string):Promise<string>;

export function GetWorkspaces():Promise<Array<main.WorkspaceInfo>>;

export function IsLoggedIn():Promise<boolean>;

export function IsWatching(arg1:string):Promise<boolean>;

export function Login():Promise<void>;

export function Logout():Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function SaveSettings(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<void>;

export function SaveTvIgnore(arg1:string,arg2:string):Promise<void>;

export function SetDeviceName(arg1:string):Promise<void>;

export function SetExcludedFolders(arg1:string,arg2:Array<string>):Promise<void>;

export function SetScheduleInterval(arg1:string,arg2:number):Promise<void>;

export function StartWatcher(arg1:string):Promise<void>;

export function StopWatcher(arg1:string):Promise<void>;

export function SyncNow(arg1:string):Promise<void>;
